/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_first;

import javax.sound.midi.*;
import static javax.sound.midi.ShortMessage.*;


public class MidiApp {
    Track track;

    private void addNote(
            int messageType,
            int instrument,
            int note,
            int velocity,
            int duration) throws javax.sound.midi.InvalidMidiDataException {
        ShortMessage msg1 = new ShortMessage();
        msg1.setMessage(messageType, instrument, note, velocity);
        MidiEvent noteOn = new MidiEvent(msg1, duration);
        track.add(noteOn);
    }

    private void playNote(int note) throws javax.sound.midi.InvalidMidiDataException {
        addNote(NOTE_ON, 1, note, 100, 1);
        addNote(NOTE_OFF, 1, note, 100, 16);
    }

    public void play() {
        try {
            Sequencer player = MidiSystem.getSequencer();
            player.open();

            Sequence seq = new Sequence(Sequence.PPQ, 4);
            track = seq.createTrack();

            // addNote(NOTE_ON, 1, 44, 100, 1);
            // addNote(NOTE_OFF, 1, 44, 100, 16);
            // addNote(NOTE_ON, 1, 44, 100, 1);
            playNote(44);
            playNote(36);


            player.setSequence(seq);
            player.start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        System.out.println("Booting app");
        MidiApp app = new MidiApp();
        app.play();
    }
}
