/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_first;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloWorldTest {
    @Test public void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
