name: Tests

on:
  push: {}

jobs:
  unit-test-gradle:
    name: Unit tests gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Lint and test
        working-directory: ./spring_boot_gradle_1
        run: |
          ./gradlew test
  
  unit-test-maven:
    name: Unit tests maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Lint and test
        working-directory: ./spring_boot_maven_1
        run: |
          ./mvnw test

  unit-test-rest-api:
    name: Unit tests rest api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Lint and test
        working-directory: ./spring_boot_rest_api
        run: |
          ./mvnw test